name: C/C++ CI

on:
  push:
    branches: [ main ]
    paths:
      - '00_Flappy_Bird/**'
  pull_request:
    branches: [ main ]
    paths:
      - '00_Flappy_Bird/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev

      - name: Configure CMake for Flappy Bird
        run: cd ./00_Flappy_Bird && cmake -S . -B build

      - name: Build
        run: cd ./00_Flappy_Bird && cmake --build build

      - name: Run tests
        run: cd ./00_Flappy_Bird && ./build/main
